### ISSUE TITLE
Theming app

### ISSUE THREAD

**Issue by fblais** [linuxmint/mint21.3-beta#14]
First time you launch the theming app, it shows the simplified form.
I then chose the "show more parameters" or whatever it's described option and did my changes.

Upon reboot, the simplified form was shown again.
I'd expect to get the full form, since I chose that beforehand.

Thanks!

**Comment by fblais** [comment]
Cinnamon DE by the way...

**Comment by mtwebster** [comment]
It won't default to showing the 'advanced settings' unless you've made some change that results in mismatched themes.

If you have, say, Mint-Y-Blue for all three (apps/icons/desktop) then switch one to pink, the next time you open theme settings it'll show advanced settings.  If you change that one back to Blue so they match again, next time you open theme settings it will show the simple view again (because your choice can be simply represented there once more).

**Comment by fblais** [comment]
Ok, I see, thanks!
